services:
  init-vol:
    image: ocrd/core
    depends_on:
      - ocrd-tesserocr
    command: sh -c "cp -rv /resources-ocrd*/* /usr/local/share/ocrd-resources; find /usr/local/share/ocrd-resources -type d -exec chmod -v 777 {} \\;; find /usr/local/share/ocrd-resources -type f -exec chmod -v 666 {} \\;"
    volumes:
      - type: volume
        source: ocrd-resources
        target: /usr/local/share/ocrd-resources
      - type: volume
        source: ocrd-tesserocr-resources
        target: /resources-ocrd-tesserocr

  ocrd-tesserocr:
    image: ocrd/tesserocr
    command: echo ""
    volumes:
      - ocrd-tesserocr-resources:/usr/local/share/ocrd-resources

volumes:
  ocrd-resources:
    external: true
  ocrd-tesserocr-resources:

