process_queue:
  address: ocrd-rabbitmq
  port: 5672
  skip_deployment: true
  credentials:
    username: admin
    password: admin
database:
  address: ocrd-mongodb
  port: 27017
  skip_deployment: true
hosts: []
