# Run "make all" on selected Ubuntu and Python versions.

name: make all

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Trigger workflow on push event.
  #push:
  #   branches: [ ci ]

  # Trigger workflow on pull request.
  # pull_request:
  #   branches: [ ci ]

  # Trigger workflow in GitHub web frontend or from API.
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system'
        required: true
        default: any
        type: choice
        options:
          - any
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
      python-version:
        description: 'Python version'
        required: true
        default: any
        type: choice
        options:
          - any
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

jobs:
  # Run builds for all Ubuntu and Python versions.
  build-any:
    # https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ (github.event.inputs.os == 'any') && (github.event.inputs.python-version == 'any') || (github.event.inputs.os == '') }}
    uses: ./.github/workflows/makeall-linux.yaml
    with:
      os: "[\'ubuntu-18.04\', \'ubuntu-20.04\', \'ubuntu-22.04\']"
      python-version: "['3.6', '3.7', '3.8', '3.9', '3.10']"

  # Run builds for all Ubuntu versions and selected Python version.
  build-any-os:
    if: ${{ (github.event.inputs.os == 'any') && (github.event.inputs.python-version != 'any') }}
    uses: ./.github/workflows/makeall-linux.yaml
    with:
      os: "[\'ubuntu-18.04\', \'ubuntu-20.04\', \'ubuntu-22.04\']"
      python-version: "[\'${{ github.event.inputs.python-version }}\']"

  # Run builds for selected Ubuntu version and all Python versions.
  build-any-python:
    if: ${{ (github.event.inputs.os != 'any') && (github.event.inputs.python-version == 'any') }}
    uses: ./.github/workflows/makeall-linux.yaml
    with:
      os: "[\'${{ github.event.inputs.os }}\']"
      python-version: "['3.6', '3.7', '3.8', '3.9', '3.10']"

  # Run builds for selected Ubuntu and Python versions.
  build:
    if: ${{ (github.event.inputs.os != 'any') && (github.event.inputs.python-version != 'any') && (github.event.inputs.os != '') }}
    uses: ./.github/workflows/makeall-linux.yaml
    with:
      os: "[\'${{ github.event.inputs.os }}\']"
      python-version: "[\'${{ github.event.inputs.python-version }}\']"
